development:
  adapter: mysql2
  encoding: utf8mb4
  database: "ttds_app"
  pool: 5
  username: root
  host: "localhost"

test:
  adapter: mysql2
  encoding: utf8mb4
  database: "ttds_app_test"
  pool: 5
  username: root
  password: 
  host: "localhost"